//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RR.DataverseAzureSql.Tests.Common.Properties
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RR.DataverseAzureSql.Tests.Common.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;BusinessUnitId&quot;: &quot;49560f2a-587e-e811-a97f-000d3a36f6bf&quot;,
        ///    &quot;CorrelationId&quot;: &quot;7ce82033-1a4b-472e-be78-8d29f3040554&quot;,
        ///    &quot;Depth&quot;: 1,
        ///    &quot;InitiatingUserAgent&quot;: &quot;Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/119.0.0.0 Safari\/537.36&quot;,
        ///    &quot;InitiatingUserAzureActiveDirectoryObjectId&quot;: &quot;a09a8ddf-c7c5-4ab9-921e-c4d348bdeec9&quot;,
        ///    &quot;InitiatingUserId&quot;: &quot;8804368a-3230-ec11-b6e5-000d3a352503&quot;,
        ///    &quot;InputParameters&quot;: [
        ///        {
        ///            &quot;key&quot;: &quot;T [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ServiceBusAssociateMessage
        {
            get
            {
                return ResourceManager.GetString("ServiceBusAssociateMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;BusinessUnitId&quot;: &quot;49560f2a-587e-e811-a97f-000d3a36f6bf&quot;,
        ///    &quot;CorrelationId&quot;: &quot;cc640ec6-64f6-4b07-8826-c131014d3b6f&quot;,
        ///    &quot;Depth&quot;: 1,
        ///    &quot;InitiatingUserAgent&quot;: &quot;Microsoft.Azure.WebJobs.Script.WebHost (DataverseSvcClient:1.0.0.26)&quot;,
        ///    &quot;InitiatingUserAzureActiveDirectoryObjectId&quot;: &quot;562efac3-7fd1-4626-b76d-6743a070ecd3&quot;,
        ///    &quot;InitiatingUserId&quot;: &quot;4b281aaa-b392-eb11-b1ac-00224802b183&quot;,
        ///    &quot;InputParameters&quot;: [
        ///        {
        ///            &quot;key&quot;: &quot;Target&quot;,
        ///            &quot;value&quot;: {
        ///                &quot;__t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ServiceBusCreateMessage
        {
            get
            {
                return ResourceManager.GetString("ServiceBusCreateMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;BusinessUnitId&quot;: &quot;49560f2a-587e-e811-a97f-000d3a36f6bf&quot;,
        ///    &quot;CorrelationId&quot;: &quot;a6b261f2-bc66-4631-991a-77e8e42ac8bd&quot;,
        ///    &quot;Depth&quot;: 0,
        ///    &quot;InitiatingUserAgent&quot;: &quot;Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/119.0.0.0 Safari\/537.36&quot;,
        ///    &quot;InitiatingUserAzureActiveDirectoryObjectId&quot;: &quot;a09a8ddf-c7c5-4ab9-921e-c4d348bdeec9&quot;,
        ///    &quot;InitiatingUserId&quot;: &quot;8804368a-3230-ec11-b6e5-000d3a352503&quot;,
        ///    &quot;InputParameters&quot;: [
        ///        {
        ///            &quot;key&quot;: &quot;T [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ServiceBusDeleteMessage
        {
            get
            {
                return ResourceManager.GetString("ServiceBusDeleteMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;BusinessUnitId&quot;: &quot;49560f2a-587e-e811-a97f-000d3a36f6bf&quot;,
        ///    &quot;CorrelationId&quot;: &quot;8985c011-b840-4499-970d-6bd5a68b6b7e&quot;,
        ///    &quot;Depth&quot;: 1,
        ///    &quot;InitiatingUserAgent&quot;: &quot;Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/119.0.0.0 Safari\/537.36&quot;,
        ///    &quot;InitiatingUserAzureActiveDirectoryObjectId&quot;: &quot;a09a8ddf-c7c5-4ab9-921e-c4d348bdeec9&quot;,
        ///    &quot;InitiatingUserId&quot;: &quot;8804368a-3230-ec11-b6e5-000d3a352503&quot;,
        ///    &quot;InputParameters&quot;: [
        ///        {
        ///            &quot;key&quot;: &quot;T [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ServiceBusDisassociateMessage
        {
            get
            {
                return ResourceManager.GetString("ServiceBusDisassociateMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;BusinessUnitId&quot;: &quot;49560f2a-587e-e811-a97f-000d3a36f6bf&quot;,
        ///    &quot;CorrelationId&quot;: &quot;a8978c3c-69c5-498f-81fe-9409ec03050d&quot;,
        ///    &quot;Depth&quot;: 1,
        ///    &quot;InitiatingUserAgent&quot;: &quot;Microsoft.Azure.WebJobs.Script.WebHost (DataverseSvcClient:1.0.0.26)&quot;,
        ///    &quot;InitiatingUserAzureActiveDirectoryObjectId&quot;: &quot;562efac3-7fd1-4626-b76d-6743a070ecd3&quot;,
        ///    &quot;InitiatingUserId&quot;: &quot;4b281aaa-b392-eb11-b1ac-00224802b183&quot;,
        ///    &quot;InputParameters&quot;: [
        ///        {
        ///            &quot;key&quot;: &quot;Target&quot;,
        ///            &quot;value&quot;: {
        ///                &quot;__t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ServiceBusUpdateMessage
        {
            get
            {
                return ResourceManager.GetString("ServiceBusUpdateMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;BusinessUnitId&quot;: &quot;49560f2a-587e-e811-a97f-000d3a36f6bf&quot;,
        ///    &quot;CorrelationId&quot;: &quot;a8978c3c-69c5-498f-81fe-9409ec03050d&quot;,
        ///    &quot;Depth&quot;: 1,
        ///    &quot;InitiatingUserAgent&quot;: &quot;Microsoft.Azure.WebJobs.Script.WebHost (DataverseSvcClient:1.0.0.26)&quot;,
        ///    &quot;InitiatingUserAzureActiveDirectoryObjectId&quot;: &quot;562efac3-7fd1-4626-b76d-6743a070ecd3&quot;,
        ///    &quot;InitiatingUserId&quot;: &quot;4b281aaa-b392-eb11-b1ac-00224802b183&quot;,
        ///    &quot;InputParameters&quot;: [
        ///        {
        ///            &quot;key&quot;: &quot;Target&quot;,
        ///            &quot;value&quot;: {
        ///                &quot;__t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ServiceBusCreateMessageWithEmptyInputParameters
        {
            get
            {
                return ResourceManager.GetString("ServiceBusCreateMessageWithEmptyInputParameters", resourceCulture);
            }
        }
    }
}
